# Configuration file for the PoG Annotator

# Main Pass Config
[main_pass]
num_workers = 4
run_passes = [
  'mgmt_pass.reorganize_folder',
  'io_pass.load_targets',
  'data_pass.load_samples',
  'face_pass.face_detect',
  'face_pass.face_embed',
  'face_pass.face_verify',
  'out_pass.local_outlier',
  'data_pass.save_samples',
]

# Data Pass Config
[data_pass]
refresh_samples = true

# Face Pass Config
[face_pass]
verify_metric = 'cosine'
verify_eps = 0.12
verify_min_samples = 8

# Outlier Pass Config
[out_pass]
verify_main_face = true
lof_min_samples = 4
lof_p_neighbors = 0.4

# Visualize Pass Config
[vis_pass]
figsize = [13, 6]
subplots_adjust = { left = 0.08, right = 0.90 }
limits = { x = [-20.0, 20.0], y = [-20.0, 0.0] }
