# Configuration file for the PoG Annotator

# Main Pass Config
[main_pass]
num_workers = 4
run_passes = [
  'io_pass.load_labels',
  'face_pass.face_detect',
  'okay_pass.local_outlier',
  'vis_pass.visualize',
]

# Face Pass Config
[face_pass]
crop_detected_face = true
purify_via_dbscan = { metric = 'cosine', eps = 0.3, min_samples = 6 }

# Okay Pass Config
[okay_pass]
min_samples = 4
p_neighbors = 0.4

# Visualize Pass Config
[vis_pass]
figsize = [13, 6]
subplots_adjust = { left = 0.08, right = 0.90 }
limits = { x = [-20.0, 20.0], y = [-20.0, 0.0] }
