# Configuration file for the PoG Annotator

# Main Pass Config
#  1. Parallel processing configuration
[main_pass]
num_workers = 4
run_passes = [
  'io_pass.load_labels',
  'face_pass.face_detect',
  'face_pass.embedding',
]

# Face Pass Config
[face_pass]
run_facenet = true
