# Configuration file for the PoG Annotator

# Main Pass Config
[main_pass]
num_workers = 4
run_passes = [
  'mgmt_pass.reorganize_folder',
  'io_pass.load_targets',
  'data_pass.load_samples',
  'face_pass.face_detect',
  'data_pass.save_samples',
]

# Data Pass Config
[data_pass]
refresh_samples = true

# Face Pass Config
[face_pass]
purify_with_dbscan = { metric = 'cosine', eps = 0.12, min_samples = 8 }

# Okay Pass Config
[okay_pass]
min_samples = 4
p_neighbors = 0.4

# Visualize Pass Config
[vis_pass]
figsize = [13, 6]
subplots_adjust = { left = 0.08, right = 0.90 }
limits = { x = [-20.0, 20.0], y = [-20.0, 0.0] }
