# Configuration for PoG Estimator

# Checkpoint path (absolute or relative to the directory of this config)
checkpoint = 'checkpoint/model.onnx'

# Resize image crops for estimator, use default: 224x224
face_resize = [224, 224]
eyes_resize = [224, 224]

# Laptop specific parameters, example (lenovo yoga c740)
#   1. ID of the camera used to capture frames
#   2. Offset of screen topleft corner in camera coordinate system
#   3. Screen size (height, weight) in pixels and centimeters
camera_id = 0
topleft_offset = [-15.5, -0.5]
screen_size_px = [1080, 1920]
screen_size_cm = [17.4, 31.0]

# Set image resolution (height, weight) for camera capture and model input
capture_resolution = [720, 1280]
target_resolution = [480, 640]

# Display the captured frame inside a preview window
#   1. Preview mode: none, full, frame
#   2. Name of the preview window
#   3. Items to display in 'full' or 'frame' preview mode
pv_mode = 'none'
pv_window = 'preview'
pv_items = ['frame', 'gaze', 'time', 'warn']

# Configuration for One-Euro filters
gx_filt_params = { beta = 0.01, min_cutoff = 0.02, d_cutoff = 1.2, clock = true }
gy_filt_params = { beta = 0.01, min_cutoff = 0.02, d_cutoff = 1.2, clock = true }

# Settings for gaze shooting game, used for server hello packet
#   1. Countdown mode: seconds, targets
#   2. Countdown value
#   3. Aiming mode: pog, key, key+pog
#   4. EnemyEmitter configs: name and extra arguments
[game_settings]
countdown = 'seconds'
value = 90
aiming = 'pog'
emitter = { name = 'demo' }
