# Configuration file for the PoG Annotator (Example)
#   This config annotates all data samples from a single subject in a multi-subjects
#   environment, where tourists standing behind the main subject will be mistakenly
#   identified as the main subject, because they might have higher face confidence
#   scores than the actual main subject
#
#   This config additionally runs two passes to detect and remove the tourists,
#   adjust the pass-specific settings according to your needs/recordings

# Main Pass Config
[main_pass]
num_workers = 4
run_passes = [
  'io_pass.load_targets',
  'data_pass.load_samples',
  'face_pass.face_detect',
  'face_pass.face_embed',
  'face_pass.face_verify',
  'out_pass.local_outlier',
  'data_pass.save_samples',
]

# Data Pass Config
[data_pass]
refresh_samples = true

# Face Pass Config
[face_pass]
verify_metric = 'cosine'
verify_eps = 0.12
verify_min_samples = 8

# Outlier Pass Config
[out_pass]
verify_main_face = true
lof_min_samples = 4
lof_p_neighbors = 0.4
