# Configuration file for the PoG Annotator (Example)
#   This config loads processed information for all data samples, then
#   visualizes the annotation results
#
#   This config depends on the output of the outlier pass

# Main Pass Config
[main_pass]
num_workers = 4
run_passes = [
  'io_pass.load_targets',
  'data_pass.load_samples',
  'vis_pass.visualize',
]

# Data Pass Config
[data_pass]
refresh_samples = false

# Visualize Pass Config
[vis_pass]
figsize = [13, 6]
subplots_adjust = { left = 0.08, right = 0.90 }
limits = { x = [-20.0, 20.0], y = [-20.0, 0.0] }
